.github/ISSUE_TEMPLATE/---bug-report.md
.github/ISSUE_TEMPLATE/---feature-request.md

- Bug template added
- Feature template added

feat(github): templates for Github added

---

backend/cli/add_interval.py
backend/cli/comand_line_parser.py
backend/cli/convert_time.py
backend/cli/db.py
backend/cli/delete_all.py
backend/cli/delete_day.py
backend/cli/delete_interval.py
backend/cli/get_slots.py
backend/cli/main.py
backend/tests/func_for_test_db.py
backend/tests/test-tool.py
backend/tests/test_add_intervals.py
backend/tests/test_db.py
backend/tests/test_delete_all.py
backend/tests/test_delete_day.py
backend/tests/test_delete_interval.py
backend/tests/test_get_slots.py
backend/tests/test_regular_day.py
backend/tests/test_regular_filter.py
backend/tests/test_regular_start_end.py
backend/tests/test_sanity.py

**What**
- added directory structure for backend
- added all files from old repository - 'play'
related #7

feat(setup): backend project setup

---

.github/workflows/python-package.yml
.gitignore
backend/requirements.txt

Github Action to run Python tests added:
- directory .github/workflows added
- file python-package.yml added
- file requirements.txt in directory backend added
related to #9

feat(GitHub Actions): Added to run Python tests

---

.github/workflows/python-package.yml

fix(pipeline): fix PR type

---

.gitignore

**What**
- add DB files in gitignore
related #15

feat(ignore): prevented commit files DB

---

.github/workflows/python-package.yml
backend/README.md
backend/bin/auto_format.py
backend/cli/add_interval.py
backend/cli/comand_line_parser.py
backend/cli/delete_all.py
backend/cli/delete_day.py
backend/cli/delete_interval.py
backend/cli/get_slots.py
backend/cli/main.py
backend/tests/test_add_intervals.py
backend/tests/test_db.py
backend/tests/test_delete_all.py
backend/tests/test_delete_day.py
backend/tests/test_delete_interval.py
backend/tests/test_get_slots.py
backend/tests/test_regular_day.py
backend/tests/test_regular_filter.py
backend/tests/test_regular_start_end.py
backend/tests/test_sanity.py
backend/tools/func_for_test_db.py
backend/tools/test-tool.py

**What**
- added README.md
- fix ImportError
- fix workflow
closes #23

fix(imports): fixed ImportError in pytest

---

backend/server/app.py
backend/tests/test_app.py

**What**
-add content test for index
-add status code test for index
related to #30

Feat(test): add test for app.py

---

.github/workflows/python-package.yml
backend/tests/test_sanity.py
backend/tools/test-tool.py

**What**
- fixed date display for `delete_day` if slots booked
- fix assert result for `delete_all`
- fixed place where test was run because changed the project structure
- fix import in `test-tool`
- removed unused imports
closed #25

Fix(sanity): fixed sanity_test

---

backend/cli/db/get_slots.py

**What**
- add function collapse_and_print_intervals
- optimized code: don't repeat
related to #44

Feat(get_slots): upgrade code

---

backend/cli/db/get_slots.py
backend/tests/test_get_slots.py
backend/tests/test_sanity.py

**What**
- fix bug: get_slots returns extra interval from the next day around midnight
- fit tests for get_slots
related to #43

Fix(get_slots): fix bug extra interval

---

package-lock.json
web/app/login.html

added fields: email address,password, button - submit/login
related #12

feat(login page): created login page

---

backend/server/static/api/meetingbook.yaml

**What**
- delete admin_in in parametrs /shedule
related #57

fix(JSON): delete admin_id

---

backend/requirements.txt
backend/tests/test_func_for_psw.py
backend/tools/func_for_psw.py

**What**
- added function for decoding header
- added function for checking password
- added function for preparing password
- added tests for all added functions
related to #64

feat(functions): Add func to prepare psw

---

backend/tests/test_func_login_with_db.py
backend/tools/create_db_for_tests.py
backend/tools/work_with_db.py

**What**
- add function for getting password from db
- add function for creating test database in memory
- add test for function get_psw
related to #49

feat(func): add func for work with db

---

backend/server/app.py
backend/server/login.py
backend/tests/test_func_for_psw.py
backend/tests/test_func_login_with_db.py
backend/tests/test_login_page.py
backend/tools/func_for_psw.py

**What**
- add blueprint for login
- add tests for login
- fix functions for passwords
- fix tests for functions
related to #50

feat(login): add blueprint for login

---

backend/tests/test_func_login_with_db.py
backend/tools/work_with_db.py

**What**
- add fuction for adding log psw in db
- add test
related #75

feat(reg): added function for registration

---

backend/server/static/api/meetingbook.yaml

**What**
- Added swagger API for POST schedule
related #68

feat(swagger): added Post for /schedule

---

backend/server/schedule_get.py
backend/tests/test_error_hendler.py

**What**
- added error_handler
- added test_error_hendler
closed #83

feat(error): added error_handler for schedule

---

backend/db/models/__init__.py
backend/server/static/api/meetingbook.yaml
backend/tests/test_get_slots_by_filter.py
backend/tests/test_get_slots_in_day.py
backend/tests/test_get_slots_in_day_by_filter.py
backend/tests/test_get_slots_in_week.py
backend/tests/test_get_slots_in_week_by_filter.py

**What**
- delete admin_in in response
- fix test for them
- fix 'status' in swagger
closed #96

fix(some errors): fix errors

---

.gitignore
backend/server/static/api/meetingbook.yaml

* bugfix: security was defined incorrectly
* add endpoint for link generation and management (https://github.com/meetingbook/meetingbook/issues/99)
* add endpoint for guest's actions (https://github.com/meetingbook/meetingbook/issues/100)
* add booking settings endpoint (https://github.com/meetingbook/meetingbook/issues/72)

Feature/99 Swagger API for guest link and more

---

backend/README.md
backend/requirements.txt
backend/server/app.py

- CORS added to app to allow all origins (*)

feat(CORS): added to app.py

---

backend/server/register.py
backend/tests/test_register_blueprint.py

**What**
- fix request body
- fix response
- fix tests
related to #76

fix(API): fix rest API for registration

---

backend/server/app.py
backend/server/auth.py
backend/server/login.py
backend/tests/test_login_page.py
webapp/src/infra/storage.js
webapp/src/infra/webservice.js
webapp/src/pages/login/index.jsx
webapp/src/pages/signup/index.jsx
webapp/src/ui/components/atoms/snackbar/index.jsx
webapp/src/ui/components/atoms/textfield/BasicTextField/index.jsx
webapp/src/ui/components/atoms/textfield/PasswordTextField/index.jsx

- Login page connected to backend
- Backend login route fixed
- CORS config fixed
closed #154
closed #56

feat(login): connect login page to the backend

---

webapp/src/pages/signup/index.jsx
webapp/src/ui/components/atoms/snackbar/infex.jsx

- added show Snackbar in case of error
related #155

feat: fix Sign Up page
